python /orions4-zfs/projects/lins2/Panos_Space/Git_Repos/tf_lab/notebooks/panos/icml/evaluating/nb_gan_jsd_evaluation.py --sample_dir /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.0 --ref /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/nips/our_synthetic_samples/ground_truth/gt_all_chair.npz --out_file /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.0/jsd_stats.txt

python /orions4-zfs/projects/lins2/Panos_Space/Git_Repos/tf_lab/notebooks/panos/icml/evaluating/nb_gan_jsd_evaluation.py --sample_dir /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/-0.9 --ref /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/nips/our_synthetic_samples/ground_truth/gt_all_chair.npz --out_file /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/-0.9/jsd_stats.txt

python /orions4-zfs/projects/lins2/Panos_Space/Git_Repos/tf_lab/notebooks/panos/icml/evaluating/nb_gan_jsd_evaluation.py --sample_dir /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.9 --ref /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/nips/our_synthetic_samples/ground_truth/gt_all_chair.npz --out_file /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.9/jsd_stats.txt

python /orions4-zfs/projects/lins2/Panos_Space/Git_Repos/tf_lab/notebooks/panos/icml/evaluating/nb_gan_jsd_evaluation.py --sample_dir /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.1 --ref /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/nips/our_synthetic_samples/ground_truth/gt_all_chair.npz --out_file /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.1/jsd_stats.txt

python /orions4-zfs/projects/lins2/Panos_Space/Git_Repos/tf_lab/notebooks/panos/icml/evaluating/nb_gan_jsd_evaluation.py --sample_dir /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/-0.1 --ref /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/nips/our_synthetic_samples/ground_truth/gt_all_chair.npz --out_file /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/-0.1/jsd_stats.txt

python /orions4-zfs/projects/lins2/Panos_Space/Git_Repos/tf_lab/notebooks/panos/icml/evaluating/nb_gan_jsd_evaluation.py --sample_dir /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/-0.5 --ref /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/nips/our_synthetic_samples/ground_truth/gt_all_chair.npz --out_file /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/-0.5/jsd_stats.txt

python /orions4-zfs/projects/lins2/Panos_Space/Git_Repos/tf_lab/notebooks/panos/icml/evaluating/nb_gan_jsd_evaluation.py --sample_dir /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.2 --ref /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/nips/our_synthetic_samples/ground_truth/gt_all_chair.npz --out_file /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.2/jsd_stats.txt

python /orions4-zfs/projects/lins2/Panos_Space/Git_Repos/tf_lab/notebooks/panos/icml/evaluating/nb_gan_jsd_evaluation.py --sample_dir /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.5 --ref /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/nips/our_synthetic_samples/ground_truth/gt_all_chair.npz --out_file /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/0.5/jsd_stats.txt

python /orions4-zfs/projects/lins2/Panos_Space/Git_Repos/tf_lab/notebooks/panos/icml/evaluating/nb_gan_jsd_evaluation.py --sample_dir /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/-0.2 --ref /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/nips/our_synthetic_samples/ground_truth/gt_all_chair.npz --out_file /orions4-zfs/projects/lins2/Panos_Space/DATA/OUT/icml/synthetic_point_clouds/momentum_search/nb_gan_ae_12_emd_chair_2048_best_epoch/-0.2/jsd_stats.txt

